import Image from "next/image";

const pillars = [
  {
    label: "0% Polyester",
    title: "No electrostatic field",
    body: "Cotton-led woven poplin removes the electrostatic charge generated by petroleum-based fibres against skin.",
  },
  {
    label: "0% Buttons",
    title: "Anatomical comfort",
    body: "A 3D-molded overlap fly replaces hardware. Zero pressure points across the inguinal region during long wear.",
  },
  {
    label: "0% Microplastics",
    title: "Roica\u2122 V550 biodegradable",
    body: "The first elastane verified to biodegrade in marine and sludge conditions, integrated at 5% for skin-safe stretch.",
  },
];

export function TripleZeroStandard() {
  return (
    <section
      id="standard"
      className="relative bg-sand-50 py-20 md:py-28 lg:py-32"
    >
      <div className="mx-auto max-w-7xl px-6 lg:px-10">
        <div className="grid gap-10 md:grid-cols-12 md:items-end">
          <div className="md:col-span-7 lg:col-span-6">
            <p className="text-xs font-medium tracking-[0.22em] text-sage-700 uppercase">
              The Triple Zero Standard
            </p>
            <h2 className="font-display mt-4 text-3xl leading-tight text-ink-900 md:text-4xl lg:text-5xl">
              A new specification for what touches you{" "}
              <em className="text-sage-700 not-italic">all day</em>.
            </h2>
          </div>
          <div className="md:col-span-5 lg:col-span-6">
            <p className="text-base leading-relaxed text-ink-700">
              Most performance underwear optimizes for compression. We optimize
              for what your body removes from circulation: synthetic polymers,
              hardware contact, and trapped heat.
            </p>
          </div>
        </div>

        <div className="mt-14 grid gap-6 md:grid-cols-12">
          <div className="shadow-sanctuary relative col-span-12 overflow-hidden rounded-3xl bg-white ring-1 ring-sage-100 md:col-span-12 lg:col-span-12">
            <div className="relative aspect-[16/8] w-full">
              <Image
                src="/images/triple-zero-standard.png"
                alt="The Triple Zero Standard: no polyester, no buttons, biodegradable"
                fill
                sizes="(min-width: 1024px) 1100px, 100vw"
                className="object-cover"
              />
            </div>
          </div>

          {pillars.map((p) => (
            <article
              key={p.label}
              className="shadow-sanctuary col-span-12 rounded-3xl bg-white p-8 ring-1 ring-sage-100 md:col-span-4"
            >
              <div className="font-display text-3xl text-sage-800">
                {p.label}
              </div>
              <h3 className="mt-4 text-lg font-medium text-ink-900">
                {p.title}
              </h3>
              <p className="mt-3 text-sm leading-relaxed text-ink-700">
                {p.body}
              </p>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
